### ISSUE TITLE
Decide how the climb maps should be setup

### ISSUE THREAD

**Issue by videoP** [videoP/racepack5#1]
Option 1: Port the boris maps directly so they can be used with q3 movement style

Option 2: Rescale the boris maps so they can be used with jka physics + ysalimari.

Option 1 would probably be better "quality" since its how it was intended to be played.
Option 2 lets it be played on servers that dont use japro to give q3 movestyle.

Maybe there could be another option but idk what

**Comment by videoP** [comment]
Well, i could set up something so that it only gives you the ysal if you are out of racemode (and i think ysal is same jumpheight as q3 so that solves that).

Then we just have to come up with how to give g_speed 320 on the non japro servers...
I guess they could just do rcon g_speed 320 but maybe there is a better way..

The map could include a saber that scales your speed to 320 maybe? but then how would you prevent them from using that on other courses..

here is a list of things you can do with .saber files:  http://pastebin.com/raw.php?i=R0gc4xk6

Could try "noFlips 1" and see if that disables forcejump, but more likely it just disables the flipping animation in forcejump...

**Comment by eternalcodes** [comment]
Option 1.
