### ISSUE TITLE
Pick some more racing maps

### ISSUE THREAD

**Issue by videoP** [videoP/racepack5#18]

**Comment by eternalcodes** [comment]
Kane wants these maps:
http://ws.q3df.org/map/jack-strafe/
http://jk2nt.cba.pl/files/maps/request.php?mapName=dfmp3_lab-inder

Dash wants these:
http://jk2nt.cba.pl/files/maps/request.php?mapName=df_wtf1
http://jk2nt.cba.pl/files/maps/request.php?mapName=dfmp1_huts
~~http://jk2nt.cba.pl/files/maps/request.php?mapName=dfmp1_hunterun~~ (confirmed)
http://jk2nt.cba.pl/files/maps/request.php?mapName=dfmp2_mafmatics
http://jk2nt.cba.pl/files/maps/request.php?mapName=dfmp2_runpharao
~~http://jk2nt.cba.pl/files/maps/request.php?mapName=dfmp3_acr08~~ (racepack4?)
http://jk2nt.cba.pl/files/maps/request.php?mapName=df_cpm10_d

**Comment by eternalcodes** [comment]
http://www.worldspawn.org/map/kabcorp-sylvan/
http://www.worldspawn.org/map/zeel-recapture/

**Comment by videoP** [comment]
links/names of the q3 versions would be better than the jk2 versions, regarding: df_wtf1, dfmp1_huts, cpm10_d
